# This file was generated by GoReleaser. DO NOT EDIT.
class Didctl < Formula
  desc "Reference client implementation for the 'bryk' DID method. The platform allows
entities to fully manage Decentralized Identifiers as described on the version
v1.0 of the specification.
"
  homepage "https://github.com/bryk-io/did-method"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bryk-io/did-method/releases/download/v0.6.1/didctl_0.6.1_darwin_amd64.tar.gz"
    sha256 "d642cd3be43fc7fa77681eb935a4da8048ca60da137309f59753812aac100e00"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/did-method/releases/download/v0.6.1/didctl_0.6.1_linux_amd64.tar.gz"
      sha256 "18ad7449ef1bbd9e412a7c44991811fefdb78533e52c1bf18d7a8e365ab6c9fc"
    end
  end

  def install
    bin.install "didctl"
    output = Utils.popen_read("#{bin}/didctl completion bash")
    (bash_completion/"didctl").write output
    output = Utils.popen_read("#{bin}/didctl completion zsh")
    (zsh_completion/"_didctl").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/didctl version"
  end
end
