# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Didctl < Formula
  desc "Reference client implementation for the 'bryk' DID method. The platform allows
entities to fully manage Decentralized Identifiers as described on the version
v1.0 of the specification.
"
  homepage "https://github.com/aidtechnology/did-method"
  version "0.9.1"

  on_macos do
    url "https://github.com/aidtechnology/did-method/releases/download/v0.9.1/didctl_0.9.1_darwin_amd64.tar.gz"
    sha256 "68dc4862efd879ef2a933d28664c1dff6a9a54202d94bff7e2e80f07475542da"

    def install
      bin.install "didctl"
      output = Utils.popen_read("#{bin}/didctl completion bash")
      (bash_completion/"didctl").write output
      output = Utils.popen_read("#{bin}/didctl completion zsh")
      (zsh_completion/"_didctl").write output
      prefix.install_metafiles
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Didctl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aidtechnology/did-method/releases/download/v0.9.1/didctl_0.9.1_linux_amd64.tar.gz"
      sha256 "e0971837b1899792757a0df8380b0eb13ad8ecee11d5640aaa9d8ef81515e007"

      def install
        bin.install "didctl"
        output = Utils.popen_read("#{bin}/didctl completion bash")
        (bash_completion/"didctl").write output
        output = Utils.popen_read("#{bin}/didctl completion zsh")
        (zsh_completion/"_didctl").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/didctl version"
  end
end
