# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Simple file system HTTP server
"
  homepage "https://github.com/bryk-io/tred-cli"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/bryk-io/serve/releases/download/v0.1.5/serve_0.1.5_darwin_amd64.tar.gz"
      sha256 "958f95d72f1ea17bd0ad7571af12a2f26cb7e78ea7865cd08426dc544d392ee4"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
    on_arm do
      url "https://github.com/bryk-io/serve/releases/download/v0.1.5/serve_0.1.5_darwin_arm64.tar.gz"
      sha256 "460fec4c65756beb6ca8624498bef0b1fd93506917822b03f8ece732a90a5e1a"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bryk-io/serve/releases/download/v0.1.5/serve_0.1.5_linux_amd64.tar.gz"
        sha256 "c6778d30c5ff76e60e3cc1f9fe39bd04b690b59d5c41cf49797f242eb45c37b1"

        def install
          bin.install "serve"
          output = Utils.popen_read("#{bin}/serve completion bash")
          (bash_completion/"serve").write output
          output = Utils.popen_read("#{bin}/serve completion zsh")
          (zsh_completion/"_serve").write output
          prefix.install_metafiles
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bryk-io/serve/releases/download/v0.1.5/serve_0.1.5_linux_arm64.tar.gz"
        sha256 "b7d48a8c70a7da83f7b429ddbcc3ab4e1fdab8353cd5175d9dbefbc84562e5c4"

        def install
          bin.install "serve"
          output = Utils.popen_read("#{bin}/serve completion bash")
          (bash_completion/"serve").write output
          output = Utils.popen_read("#{bin}/serve completion zsh")
          (zsh_completion/"_serve").write output
          prefix.install_metafiles
        end
      end
    end
  end

  test do
    system "#{bin}/serve version"
  end
end
