# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Simple file system HTTP server
"
  homepage "https://github.com/bryk-io/tred-cli"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.3/serve_0.1.3_darwin_amd64.tar.gz"
      sha256 "e403f2abb2bf48e70e03d454223b6c2ab6e4cefce68f907abd870fb5353715c1"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.3/serve_0.1.3_darwin_arm64.tar.gz"
      sha256 "212db321039285208be0cad07a9dfcc44b4c44217d9e4e83ac568e99f7f3d576"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.3/serve_0.1.3_linux_arm64.tar.gz"
      sha256 "776158ce92390b445a41bf161734196fb4694b0a4442ae94c1df9c13c7e90289"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.3/serve_0.1.3_linux_amd64.tar.gz"
      sha256 "65f3ce8293ae057cf06233af8413f7f035789401a70e8001b68f0708e29e120f"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/serve version"
  end
end
