# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Simple file system HTTP server
"
  homepage "https://github.com/bryk-io/tred-cli"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.4/serve_0.1.4_darwin_arm64.tar.gz"
      sha256 "04de03543d3b2cdeb21f65d178b86063894e3b373b6669be4f4b5ae4f11cd605"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.4/serve_0.1.4_darwin_amd64.tar.gz"
      sha256 "4307aefaedac5344a8647370076478b3a2851c7dcef3449f5157b053faace0a0"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.4/serve_0.1.4_linux_amd64.tar.gz"
      sha256 "9711570582687930bce90f94def352b521a94922a8a9b58efa1692007983b60b"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bryk-io/serve/releases/download/v0.1.4/serve_0.1.4_linux_arm64.tar.gz"
      sha256 "8429a1e38b02d62f6981e10a2deba3c54e28538928ef7a119cdcff2662a29359"

      def install
        bin.install "serve"
        output = Utils.popen_read("#{bin}/serve completion bash")
        (bash_completion/"serve").write output
        output = Utils.popen_read("#{bin}/serve completion zsh")
        (zsh_completion/"_serve").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/serve version"
  end
end
