# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tredctl < Formula
  desc "CLI client for the 'Tamper Resistant Encrypted Data' protocol.
"
  homepage "https://github.com/bryk-io/tred-cli"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/tred-cli/releases/download/v0.6.1/tredctl_0.6.1_darwin_amd64.tar.gz"
      sha256 "34d467e69d9936af807c96f2f7ddfb69da3242d67774e54503b40148c5029711"

      def install
        bin.install "tredctl"
        output = Utils.popen_read("#{bin}/tredctl completion bash")
        (bash_completion/"tredctl").write output
        output = Utils.popen_read("#{bin}/tredctl completion zsh")
        (zsh_completion/"_tredctl").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bryk-io/tred-cli/releases/download/v0.6.1/tredctl_0.6.1_darwin_arm64.tar.gz"
      sha256 "076deeee26c2750f2d3065a1ffe3c33b8c3aabc09182a0dd9be1aee3fc2c1b36"

      def install
        bin.install "tredctl"
        output = Utils.popen_read("#{bin}/tredctl completion bash")
        (bash_completion/"tredctl").write output
        output = Utils.popen_read("#{bin}/tredctl completion zsh")
        (zsh_completion/"_tredctl").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bryk-io/tred-cli/releases/download/v0.6.1/tredctl_0.6.1_linux_arm64.tar.gz"
      sha256 "16253a992a93ab56fa8ec98a0225a522ab8d2d37fb5133efbd5a65d23fbe55e1"

      def install
        bin.install "tredctl"
        output = Utils.popen_read("#{bin}/tredctl completion bash")
        (bash_completion/"tredctl").write output
        output = Utils.popen_read("#{bin}/tredctl completion zsh")
        (zsh_completion/"_tredctl").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bryk-io/tred-cli/releases/download/v0.6.1/tredctl_0.6.1_linux_amd64.tar.gz"
      sha256 "e0034a3e1e808887f705d7f8af46f5fbd4b2c2e3ad2194acc40b644929de030f"

      def install
        bin.install "tredctl"
        output = Utils.popen_read("#{bin}/tredctl completion bash")
        (bash_completion/"tredctl").write output
        output = Utils.popen_read("#{bin}/tredctl completion zsh")
        (zsh_completion/"_tredctl").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/tredctl version"
  end
end
